version: "3"
services:
  app:
    container_name: app
    restart: always
    build: app/
    ports:
      - "20000:20000"
  api:
    container_name: api
    build: api/
    restart: always
    depends_on:
      - mongo
    ports:
      - "10000:10000"
  auth:
    container_name: auth
    build: auth/
    restart: always
    depends_on:
      - mongo
    ports:
      - "30000:30000"
  mongo:
    image: mongo
    ports:
      - 27017:27017
